package org.rbbozkurt.composescriptrunner.ui.state

/**
 * Represents the state of the output pane that displays the results of a script execution.
 */
sealed class OutputPaneUiState {

    /**
     * Indicates that the output pane is idle, waiting for a script to be run.
     */
    object Idle : OutputPaneUiState()

    /**
     * Indicates that a script is currently running.
     */
    object Running : OutputPaneUiState()

    /**
     * Represents a successful script execution.
     *
     * @param output The output generated by the script.
     * @param exitCode The exit code returned by the script (expected to be 0).
     */
    data class Success(
        val output: String,
        val exitCode: Int
    ) : OutputPaneUiState()

    /**
     * Represents a script execution that resulted in an error.
     *
     * @param message The error message or output generated by the script.
     * @param exitCode The exit code returned by the script (non-zero), if available.
     */
    data class Error(
        val message: String,
        val exitCode: Int? = null
    ) : OutputPaneUiState()
}
